export const BOOK_EASE = [0.77, 0, 0.175, 1] as const;

export const PAGE_FLIP_DURATION_MS = 850;

export const CONTENT_NAVIGATION_FLIP_DURATION_MS =
  PAGE_FLIP_DURATION_MS / 2;

export const COVER_TRANSITION_DURATION_MS = 360;

export const PAGE_FLIP_DURATION_SECONDS =
  PAGE_FLIP_DURATION_MS / 1000;

export const COVER_TRANSITION_DURATION_SECONDS =
  COVER_TRANSITION_DURATION_MS / 1000;
